// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package github

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/Khan/genqlient/graphql"
)

// The reason you received a notification about a subject.
type NotificationReason string

const (
	// You were assigned to the Issue/PR.
	NotificationReasonAssign NotificationReason = "ASSIGN"
	// You created the thread.
	NotificationReasonAuthor NotificationReason = "AUTHOR"
	// You commented on the thread.
	NotificationReasonComment NotificationReason = "COMMENT"
	// You accepted an invitation to contribute to the repository.
	NotificationReasonInvitation NotificationReason = "INVITATION"
	// You subscribed to the thread (via an Issue or Pull Request).
	NotificationReasonManual NotificationReason = "MANUAL"
	// You were specifically @mentioned in the content.
	NotificationReasonMention NotificationReason = "MENTION"
	// You were requested for review.
	NotificationReasonReviewRequested NotificationReason = "REVIEW_REQUESTED"
	// You were given credit for contributing to a Security Advisory.
	NotificationReasonSecurityAdvisoryCredit NotificationReason = "SECURITY_ADVISORY_CREDIT"
	// You have access to the notification subject's Dependabot alerts.
	NotificationReasonSecurityAlert NotificationReason = "SECURITY_ALERT"
	// You changed the thread state (for example, closing an Issue or merging a Pull Request).
	NotificationReasonStateChange NotificationReason = "STATE_CHANGE"
	// You are watching the subject of the notification.
	NotificationReasonSubscribed NotificationReason = "SUBSCRIBED"
	// You were on a team that was mentioned.
	NotificationReasonTeamMention NotificationReason = "TEAM_MENTION"
	// You are subscribed to continuous integration activity.
	NotificationReasonCiActivity NotificationReason = "CI_ACTIVITY"
	// You were requested for review for deployment.
	NotificationReasonApprovalRequested NotificationReason = "APPROVAL_REQUESTED"
	// You saved this notification
	NotificationReasonSaved NotificationReason = "SAVED"
	// A pull request you're subscribed to was marked ready for review.
	NotificationReasonReadyForReview NotificationReason = "READY_FOR_REVIEW"
	// New requests from members.
	NotificationReasonMemberFeatureRequested NotificationReason = "MEMBER_FEATURE_REQUESTED"
)

var AllNotificationReason = []NotificationReason{
	NotificationReasonAssign,
	NotificationReasonAuthor,
	NotificationReasonComment,
	NotificationReasonInvitation,
	NotificationReasonManual,
	NotificationReasonMention,
	NotificationReasonReviewRequested,
	NotificationReasonSecurityAdvisoryCredit,
	NotificationReasonSecurityAlert,
	NotificationReasonStateChange,
	NotificationReasonSubscribed,
	NotificationReasonTeamMention,
	NotificationReasonCiActivity,
	NotificationReasonApprovalRequested,
	NotificationReasonSaved,
	NotificationReasonReadyForReview,
	NotificationReasonMemberFeatureRequested,
}

// TestingResponse is returned by Testing on success.
type TestingResponse struct {
	// The currently authenticated user.
	Viewer TestingViewerUser `json:"viewer"`
}

// GetViewer returns TestingResponse.Viewer, and is useful for accessing the field via an interface.
func (v *TestingResponse) GetViewer() TestingViewerUser { return v.Viewer }

// TestingViewerUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A user is an individual's account on GitHub that owns repositories and can make new content.
type TestingViewerUser struct {
	// A list of notification threads for the viewer. Returns an empty list for a user other than
	// the current viewer.
	//
	// Combining both filterBy and query arguments will result in an error.
	// Please favor using the query argument.
	NotificationThreads TestingViewerUserNotificationThreadsNotificationThreadConnection `json:"notificationThreads"`
}

// GetNotificationThreads returns TestingViewerUser.NotificationThreads, and is useful for accessing the field via an interface.
func (v *TestingViewerUser) GetNotificationThreads() TestingViewerUserNotificationThreadsNotificationThreadConnection {
	return v.NotificationThreads
}

// TestingViewerUserNotificationThreadsNotificationThreadConnection includes the requested fields of the GraphQL type NotificationThreadConnection.
// The GraphQL type's documentation follows.
//
// A list of notification threads.
type TestingViewerUserNotificationThreadsNotificationThreadConnection struct {
	// A list of edges.
	Edges []TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdge `json:"edges"`
}

// GetEdges returns TestingViewerUserNotificationThreadsNotificationThreadConnection.Edges, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnection) GetEdges() []TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdge {
	return v.Edges
}

// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdge includes the requested fields of the GraphQL type NotificationThreadEdge.
// The GraphQL type's documentation follows.
//
// An edge in a connection.
type TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdge struct {
	// A cursor for use in pagination.
	Cursor string `json:"cursor"`
	// The item at the end of the edge.
	Node TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThread `json:"node"`
}

// GetCursor returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdge.Cursor, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdge) GetCursor() string {
	return v.Cursor
}

// GetNode returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdge.Node, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdge) GetNode() TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThread {
	return v.Node
}

// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThread includes the requested fields of the GraphQL type NotificationThread.
// The GraphQL type's documentation follows.
//
// Represents a notification thread for the viewer.
type TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThread struct {
	// The Node ID of the NotificationThread object
	Id string `json:"id"`
	// The oldest unread author internal anchor
	OldestUnreadItemAnchor string `json:"oldestUnreadItemAnchor"`
	// The reason a notification was received.
	Reason NotificationReason `json:"reason"`
	// The notification's title
	Title string `json:"title"`
	// Unread state of the notification.
	IsUnread bool `json:"isUnread"`
	// Done state of the notification.
	IsDone bool `json:"isDone"`
	// Whether a notification has been saved
	IsSaved bool `json:"isSaved"`
	// Whether a notification has been starred
	IsStarred bool `json:"isStarred"`
	// The last time that notifications were read for this thread.
	LastReadAt time.Time `json:"lastReadAt"`
	// The last time that a notification was received on this thread for the current user
	LastUpdatedAt time.Time `json:"lastUpdatedAt"`
	// The HTTP URL for the notification thread's subject
	Url string `json:"url"`
	// The notification's subject.
	OptionalSubject TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectNotificationsSubject `json:"-"`
}

// GetId returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThread.Id, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThread) GetId() string {
	return v.Id
}

// GetOldestUnreadItemAnchor returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThread.OldestUnreadItemAnchor, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThread) GetOldestUnreadItemAnchor() string {
	return v.OldestUnreadItemAnchor
}

// GetReason returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThread.Reason, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThread) GetReason() NotificationReason {
	return v.Reason
}

// GetTitle returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThread.Title, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThread) GetTitle() string {
	return v.Title
}

// GetIsUnread returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThread.IsUnread, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThread) GetIsUnread() bool {
	return v.IsUnread
}

// GetIsDone returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThread.IsDone, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThread) GetIsDone() bool {
	return v.IsDone
}

// GetIsSaved returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThread.IsSaved, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThread) GetIsSaved() bool {
	return v.IsSaved
}

// GetIsStarred returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThread.IsStarred, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThread) GetIsStarred() bool {
	return v.IsStarred
}

// GetLastReadAt returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThread.LastReadAt, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThread) GetLastReadAt() time.Time {
	return v.LastReadAt
}

// GetLastUpdatedAt returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThread.LastUpdatedAt, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThread) GetLastUpdatedAt() time.Time {
	return v.LastUpdatedAt
}

// GetUrl returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThread.Url, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThread) GetUrl() string {
	return v.Url
}

// GetOptionalSubject returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThread.OptionalSubject, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThread) GetOptionalSubject() TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectNotificationsSubject {
	return v.OptionalSubject
}

func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThread) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThread
		OptionalSubject json.RawMessage `json:"optionalSubject"`
		graphql.NoUnmarshalJSON
	}
	firstPass.TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThread = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.OptionalSubject
		src := firstPass.OptionalSubject
		if len(src) != 0 && string(src) != "null" {
			err = __unmarshalTestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectNotificationsSubject(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThread.OptionalSubject: %w", err)
			}
		}
	}
	return nil
}

type __premarshalTestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThread struct {
	Id string `json:"id"`

	OldestUnreadItemAnchor string `json:"oldestUnreadItemAnchor"`

	Reason NotificationReason `json:"reason"`

	Title string `json:"title"`

	IsUnread bool `json:"isUnread"`

	IsDone bool `json:"isDone"`

	IsSaved bool `json:"isSaved"`

	IsStarred bool `json:"isStarred"`

	LastReadAt time.Time `json:"lastReadAt"`

	LastUpdatedAt time.Time `json:"lastUpdatedAt"`

	Url string `json:"url"`

	OptionalSubject json.RawMessage `json:"optionalSubject"`
}

func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThread) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThread) __premarshalJSON() (*__premarshalTestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThread, error) {
	var retval __premarshalTestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThread

	retval.Id = v.Id
	retval.OldestUnreadItemAnchor = v.OldestUnreadItemAnchor
	retval.Reason = v.Reason
	retval.Title = v.Title
	retval.IsUnread = v.IsUnread
	retval.IsDone = v.IsDone
	retval.IsSaved = v.IsSaved
	retval.IsStarred = v.IsStarred
	retval.LastReadAt = v.LastReadAt
	retval.LastUpdatedAt = v.LastUpdatedAt
	retval.Url = v.Url
	{

		dst := &retval.OptionalSubject
		src := v.OptionalSubject
		var err error
		*dst, err = __marshalTestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectNotificationsSubject(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThread.OptionalSubject: %w", err)
		}
	}
	return &retval, nil
}

// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectCheckSuite includes the requested fields of the GraphQL type CheckSuite.
// The GraphQL type's documentation follows.
//
// A check suite.
type TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectCheckSuite struct {
	Typename string `json:"__typename"`
}

// GetTypename returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectCheckSuite.Typename, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectCheckSuite) GetTypename() string {
	return v.Typename
}

// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectCommit includes the requested fields of the GraphQL type Commit.
// The GraphQL type's documentation follows.
//
// Represents a Git commit.
type TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectCommit struct {
	Typename string `json:"__typename"`
}

// GetTypename returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectCommit.Typename, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectCommit) GetTypename() string {
	return v.Typename
}

// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectDiscussion includes the requested fields of the GraphQL type Discussion.
// The GraphQL type's documentation follows.
//
// A discussion in a repository.
type TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectDiscussion struct {
	Typename string `json:"__typename"`
}

// GetTypename returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectDiscussion.Typename, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectDiscussion) GetTypename() string {
	return v.Typename
}

// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectGist includes the requested fields of the GraphQL type Gist.
// The GraphQL type's documentation follows.
//
// A Gist.
type TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectGist struct {
	Typename string `json:"__typename"`
}

// GetTypename returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectGist.Typename, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectGist) GetTypename() string {
	return v.Typename
}

// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectIssue includes the requested fields of the GraphQL type Issue.
// The GraphQL type's documentation follows.
//
// An Issue is a place to discuss ideas, enhancements, tasks, and bugs for a project.
type TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectIssue struct {
	Typename string `json:"__typename"`
}

// GetTypename returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectIssue.Typename, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectIssue) GetTypename() string {
	return v.Typename
}

// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectMemberFeatureRequestNotification includes the requested fields of the GraphQL type MemberFeatureRequestNotification.
// The GraphQL type's documentation follows.
//
// Represents a member feature request notification
type TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectMemberFeatureRequestNotification struct {
	Typename string `json:"__typename"`
}

// GetTypename returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectMemberFeatureRequestNotification.Typename, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectMemberFeatureRequestNotification) GetTypename() string {
	return v.Typename
}

// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectNotificationsSubject includes the requested fields of the GraphQL interface NotificationsSubject.
//
// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectNotificationsSubject is implemented by the following types:
// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectCheckSuite
// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectCommit
// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectDiscussion
// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectGist
// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectIssue
// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectMemberFeatureRequestNotification
// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectProjectV2
// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequest
// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectRelease
// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectRepositoryDependabotAlertsThread
// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectRepositoryInvitation
// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectRepositoryVulnerabilityAlert
// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectSecurityAdvisory
// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectWorkflowRun
// The GraphQL type's documentation follows.
//
// The notification's subject.
type TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectNotificationsSubject interface {
	implementsGraphQLInterfaceTestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectNotificationsSubject()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() string
}

func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectCheckSuite) implementsGraphQLInterfaceTestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectNotificationsSubject() {
}
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectCommit) implementsGraphQLInterfaceTestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectNotificationsSubject() {
}
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectDiscussion) implementsGraphQLInterfaceTestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectNotificationsSubject() {
}
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectGist) implementsGraphQLInterfaceTestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectNotificationsSubject() {
}
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectIssue) implementsGraphQLInterfaceTestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectNotificationsSubject() {
}
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectMemberFeatureRequestNotification) implementsGraphQLInterfaceTestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectNotificationsSubject() {
}
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectProjectV2) implementsGraphQLInterfaceTestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectNotificationsSubject() {
}
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequest) implementsGraphQLInterfaceTestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectNotificationsSubject() {
}
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectRelease) implementsGraphQLInterfaceTestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectNotificationsSubject() {
}
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectRepositoryDependabotAlertsThread) implementsGraphQLInterfaceTestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectNotificationsSubject() {
}
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectRepositoryInvitation) implementsGraphQLInterfaceTestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectNotificationsSubject() {
}
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectRepositoryVulnerabilityAlert) implementsGraphQLInterfaceTestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectNotificationsSubject() {
}
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectSecurityAdvisory) implementsGraphQLInterfaceTestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectNotificationsSubject() {
}
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectWorkflowRun) implementsGraphQLInterfaceTestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectNotificationsSubject() {
}

func __unmarshalTestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectNotificationsSubject(b []byte, v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectNotificationsSubject) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "CheckSuite":
		*v = new(TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectCheckSuite)
		return json.Unmarshal(b, *v)
	case "Commit":
		*v = new(TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectCommit)
		return json.Unmarshal(b, *v)
	case "Discussion":
		*v = new(TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectDiscussion)
		return json.Unmarshal(b, *v)
	case "Gist":
		*v = new(TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectGist)
		return json.Unmarshal(b, *v)
	case "Issue":
		*v = new(TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectIssue)
		return json.Unmarshal(b, *v)
	case "MemberFeatureRequestNotification":
		*v = new(TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectMemberFeatureRequestNotification)
		return json.Unmarshal(b, *v)
	case "ProjectV2":
		*v = new(TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectProjectV2)
		return json.Unmarshal(b, *v)
	case "PullRequest":
		*v = new(TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequest)
		return json.Unmarshal(b, *v)
	case "Release":
		*v = new(TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectRelease)
		return json.Unmarshal(b, *v)
	case "RepositoryDependabotAlertsThread":
		*v = new(TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectRepositoryDependabotAlertsThread)
		return json.Unmarshal(b, *v)
	case "RepositoryInvitation":
		*v = new(TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectRepositoryInvitation)
		return json.Unmarshal(b, *v)
	case "RepositoryVulnerabilityAlert":
		*v = new(TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectRepositoryVulnerabilityAlert)
		return json.Unmarshal(b, *v)
	case "SecurityAdvisory":
		*v = new(TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectSecurityAdvisory)
		return json.Unmarshal(b, *v)
	case "WorkflowRun":
		*v = new(TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectWorkflowRun)
		return json.Unmarshal(b, *v)
	case "":
		return fmt.Errorf(
			"response was missing NotificationsSubject.__typename")
	default:
		return fmt.Errorf(
			`unexpected concrete type for TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectNotificationsSubject: "%v"`, tn.TypeName)
	}
}

func __marshalTestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectNotificationsSubject(v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectNotificationsSubject) ([]byte, error) {

	var typename string
	switch v := (*v).(type) {
	case *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectCheckSuite:
		typename = "CheckSuite"

		result := struct {
			TypeName string `json:"__typename"`
			*TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectCheckSuite
		}{typename, v}
		return json.Marshal(result)
	case *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectCommit:
		typename = "Commit"

		result := struct {
			TypeName string `json:"__typename"`
			*TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectCommit
		}{typename, v}
		return json.Marshal(result)
	case *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectDiscussion:
		typename = "Discussion"

		result := struct {
			TypeName string `json:"__typename"`
			*TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectDiscussion
		}{typename, v}
		return json.Marshal(result)
	case *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectGist:
		typename = "Gist"

		result := struct {
			TypeName string `json:"__typename"`
			*TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectGist
		}{typename, v}
		return json.Marshal(result)
	case *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectIssue:
		typename = "Issue"

		result := struct {
			TypeName string `json:"__typename"`
			*TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectIssue
		}{typename, v}
		return json.Marshal(result)
	case *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectMemberFeatureRequestNotification:
		typename = "MemberFeatureRequestNotification"

		result := struct {
			TypeName string `json:"__typename"`
			*TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectMemberFeatureRequestNotification
		}{typename, v}
		return json.Marshal(result)
	case *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectProjectV2:
		typename = "ProjectV2"

		result := struct {
			TypeName string `json:"__typename"`
			*TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectProjectV2
		}{typename, v}
		return json.Marshal(result)
	case *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequest:
		typename = "PullRequest"

		premarshaled, err := v.__premarshalJSON()
		if err != nil {
			return nil, err
		}
		result := struct {
			TypeName string `json:"__typename"`
			*__premarshalTestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequest
		}{typename, premarshaled}
		return json.Marshal(result)
	case *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectRelease:
		typename = "Release"

		result := struct {
			TypeName string `json:"__typename"`
			*TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectRelease
		}{typename, v}
		return json.Marshal(result)
	case *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectRepositoryDependabotAlertsThread:
		typename = "RepositoryDependabotAlertsThread"

		result := struct {
			TypeName string `json:"__typename"`
			*TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectRepositoryDependabotAlertsThread
		}{typename, v}
		return json.Marshal(result)
	case *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectRepositoryInvitation:
		typename = "RepositoryInvitation"

		result := struct {
			TypeName string `json:"__typename"`
			*TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectRepositoryInvitation
		}{typename, v}
		return json.Marshal(result)
	case *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectRepositoryVulnerabilityAlert:
		typename = "RepositoryVulnerabilityAlert"

		result := struct {
			TypeName string `json:"__typename"`
			*TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectRepositoryVulnerabilityAlert
		}{typename, v}
		return json.Marshal(result)
	case *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectSecurityAdvisory:
		typename = "SecurityAdvisory"

		result := struct {
			TypeName string `json:"__typename"`
			*TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectSecurityAdvisory
		}{typename, v}
		return json.Marshal(result)
	case *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectWorkflowRun:
		typename = "WorkflowRun"

		result := struct {
			TypeName string `json:"__typename"`
			*TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectWorkflowRun
		}{typename, v}
		return json.Marshal(result)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`unexpected concrete type for TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectNotificationsSubject: "%T"`, v)
	}
}

// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectProjectV2 includes the requested fields of the GraphQL type ProjectV2.
// The GraphQL type's documentation follows.
//
// New projects that manage issues, pull requests and drafts using tables and boards.
type TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectProjectV2 struct {
	Typename string `json:"__typename"`
}

// GetTypename returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectProjectV2.Typename, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectProjectV2) GetTypename() string {
	return v.Typename
}

// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequest includes the requested fields of the GraphQL type PullRequest.
// The GraphQL type's documentation follows.
//
// A repository pull request.
type TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequest struct {
	Typename string `json:"__typename"`
	// Identifies the pull request title.
	Title string `json:"title"`
	// The body as Markdown.
	Body string `json:"body"`
	// The actor who authored the comment.
	Author TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorActor `json:"-"`
	// Whether or not the pull request was merged.
	Merged bool `json:"merged"`
	// `true` if the pull request is closed
	Closed bool `json:"closed"`
}

// GetTypename returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequest.Typename, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequest) GetTypename() string {
	return v.Typename
}

// GetTitle returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequest.Title, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequest) GetTitle() string {
	return v.Title
}

// GetBody returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequest.Body, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequest) GetBody() string {
	return v.Body
}

// GetAuthor returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequest.Author, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequest) GetAuthor() TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorActor {
	return v.Author
}

// GetMerged returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequest.Merged, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequest) GetMerged() bool {
	return v.Merged
}

// GetClosed returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequest.Closed, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequest) GetClosed() bool {
	return v.Closed
}

func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequest) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequest
		Author json.RawMessage `json:"author"`
		graphql.NoUnmarshalJSON
	}
	firstPass.TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequest = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.Author
		src := firstPass.Author
		if len(src) != 0 && string(src) != "null" {
			err = __unmarshalTestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorActor(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"unable to unmarshal TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequest.Author: %w", err)
			}
		}
	}
	return nil
}

type __premarshalTestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequest struct {
	Typename string `json:"__typename"`

	Title string `json:"title"`

	Body string `json:"body"`

	Author json.RawMessage `json:"author"`

	Merged bool `json:"merged"`

	Closed bool `json:"closed"`
}

func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequest) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequest) __premarshalJSON() (*__premarshalTestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequest, error) {
	var retval __premarshalTestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequest

	retval.Typename = v.Typename
	retval.Title = v.Title
	retval.Body = v.Body
	{

		dst := &retval.Author
		src := v.Author
		var err error
		*dst, err = __marshalTestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorActor(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"unable to marshal TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequest.Author: %w", err)
		}
	}
	retval.Merged = v.Merged
	retval.Closed = v.Closed
	return &retval, nil
}

// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorActor includes the requested fields of the GraphQL interface Actor.
//
// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorActor is implemented by the following types:
// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorBot
// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorEnterpriseUserAccount
// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorMannequin
// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorOrganization
// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorUser
// The GraphQL type's documentation follows.
//
// Represents an object which can take actions on GitHub. Typically a User or Bot.
type TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorActor interface {
	implementsGraphQLInterfaceTestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorActor()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() string
}

func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorBot) implementsGraphQLInterfaceTestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorActor() {
}
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorEnterpriseUserAccount) implementsGraphQLInterfaceTestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorActor() {
}
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorMannequin) implementsGraphQLInterfaceTestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorActor() {
}
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorOrganization) implementsGraphQLInterfaceTestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorActor() {
}
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorUser) implementsGraphQLInterfaceTestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorActor() {
}

func __unmarshalTestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorActor(b []byte, v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorActor) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "Bot":
		*v = new(TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorBot)
		return json.Unmarshal(b, *v)
	case "EnterpriseUserAccount":
		*v = new(TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorEnterpriseUserAccount)
		return json.Unmarshal(b, *v)
	case "Mannequin":
		*v = new(TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorMannequin)
		return json.Unmarshal(b, *v)
	case "Organization":
		*v = new(TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorOrganization)
		return json.Unmarshal(b, *v)
	case "User":
		*v = new(TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorUser)
		return json.Unmarshal(b, *v)
	case "":
		return fmt.Errorf(
			"response was missing Actor.__typename")
	default:
		return fmt.Errorf(
			`unexpected concrete type for TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorActor: "%v"`, tn.TypeName)
	}
}

func __marshalTestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorActor(v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorActor) ([]byte, error) {

	var typename string
	switch v := (*v).(type) {
	case *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorBot:
		typename = "Bot"

		result := struct {
			TypeName string `json:"__typename"`
			*TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorBot
		}{typename, v}
		return json.Marshal(result)
	case *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorEnterpriseUserAccount:
		typename = "EnterpriseUserAccount"

		result := struct {
			TypeName string `json:"__typename"`
			*TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorEnterpriseUserAccount
		}{typename, v}
		return json.Marshal(result)
	case *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorMannequin:
		typename = "Mannequin"

		result := struct {
			TypeName string `json:"__typename"`
			*TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorMannequin
		}{typename, v}
		return json.Marshal(result)
	case *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorOrganization:
		typename = "Organization"

		result := struct {
			TypeName string `json:"__typename"`
			*TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorOrganization
		}{typename, v}
		return json.Marshal(result)
	case *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorUser:
		typename = "User"

		result := struct {
			TypeName string `json:"__typename"`
			*TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorUser
		}{typename, v}
		return json.Marshal(result)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`unexpected concrete type for TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorActor: "%T"`, v)
	}
}

// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorBot includes the requested fields of the GraphQL type Bot.
// The GraphQL type's documentation follows.
//
// A special type of user which takes actions on behalf of GitHub Apps.
type TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorBot struct {
	Typename string `json:"__typename"`
	// The username of the actor.
	Login string `json:"login"`
}

// GetTypename returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorBot.Typename, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorBot) GetTypename() string {
	return v.Typename
}

// GetLogin returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorBot.Login, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorBot) GetLogin() string {
	return v.Login
}

// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorEnterpriseUserAccount includes the requested fields of the GraphQL type EnterpriseUserAccount.
// The GraphQL type's documentation follows.
//
// An account for a user who is an admin of an enterprise or a member of an enterprise through one or more organizations.
type TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorEnterpriseUserAccount struct {
	Typename string `json:"__typename"`
}

// GetTypename returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorEnterpriseUserAccount.Typename, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorEnterpriseUserAccount) GetTypename() string {
	return v.Typename
}

// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorMannequin includes the requested fields of the GraphQL type Mannequin.
// The GraphQL type's documentation follows.
//
// A placeholder user for attribution of imported data on GitHub.
type TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorMannequin struct {
	Typename string `json:"__typename"`
}

// GetTypename returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorMannequin.Typename, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorMannequin) GetTypename() string {
	return v.Typename
}

// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorOrganization includes the requested fields of the GraphQL type Organization.
// The GraphQL type's documentation follows.
//
// An account on GitHub, with one or more owners, that has repositories, members and teams.
type TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorOrganization struct {
	Typename string `json:"__typename"`
}

// GetTypename returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorOrganization.Typename, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorOrganization) GetTypename() string {
	return v.Typename
}

// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorUser includes the requested fields of the GraphQL type User.
// The GraphQL type's documentation follows.
//
// A user is an individual's account on GitHub that owns repositories and can make new content.
type TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorUser struct {
	Typename string `json:"__typename"`
	// The user's public profile name.
	Name string `json:"name"`
	// The username used to login.
	Login string `json:"login"`
}

// GetTypename returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorUser.Typename, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorUser) GetTypename() string {
	return v.Typename
}

// GetName returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorUser.Name, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorUser) GetName() string {
	return v.Name
}

// GetLogin returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorUser.Login, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectPullRequestAuthorUser) GetLogin() string {
	return v.Login
}

// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectRelease includes the requested fields of the GraphQL type Release.
// The GraphQL type's documentation follows.
//
// A release contains the content for a release.
type TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectRelease struct {
	Typename string `json:"__typename"`
}

// GetTypename returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectRelease.Typename, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectRelease) GetTypename() string {
	return v.Typename
}

// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectRepositoryDependabotAlertsThread includes the requested fields of the GraphQL type RepositoryDependabotAlertsThread.
// The GraphQL type's documentation follows.
//
// A wrapper on Repository used for Dependabot Alerts notifications.
type TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectRepositoryDependabotAlertsThread struct {
	Typename string `json:"__typename"`
}

// GetTypename returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectRepositoryDependabotAlertsThread.Typename, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectRepositoryDependabotAlertsThread) GetTypename() string {
	return v.Typename
}

// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectRepositoryInvitation includes the requested fields of the GraphQL type RepositoryInvitation.
// The GraphQL type's documentation follows.
//
// An invitation for a user to be added to a repository.
type TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectRepositoryInvitation struct {
	Typename string `json:"__typename"`
}

// GetTypename returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectRepositoryInvitation.Typename, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectRepositoryInvitation) GetTypename() string {
	return v.Typename
}

// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectRepositoryVulnerabilityAlert includes the requested fields of the GraphQL type RepositoryVulnerabilityAlert.
// The GraphQL type's documentation follows.
//
// A Dependabot alert for a repository with a dependency affected by a security vulnerability.
type TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectRepositoryVulnerabilityAlert struct {
	Typename string `json:"__typename"`
}

// GetTypename returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectRepositoryVulnerabilityAlert.Typename, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectRepositoryVulnerabilityAlert) GetTypename() string {
	return v.Typename
}

// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectSecurityAdvisory includes the requested fields of the GraphQL type SecurityAdvisory.
// The GraphQL type's documentation follows.
//
// A GitHub Security Advisory
type TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectSecurityAdvisory struct {
	Typename string `json:"__typename"`
}

// GetTypename returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectSecurityAdvisory.Typename, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectSecurityAdvisory) GetTypename() string {
	return v.Typename
}

// TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectWorkflowRun includes the requested fields of the GraphQL type WorkflowRun.
// The GraphQL type's documentation follows.
//
// A workflow run.
type TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectWorkflowRun struct {
	Typename string `json:"__typename"`
}

// GetTypename returns TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectWorkflowRun.Typename, and is useful for accessing the field via an interface.
func (v *TestingViewerUserNotificationThreadsNotificationThreadConnectionEdgesNotificationThreadEdgeNodeNotificationThreadOptionalSubjectWorkflowRun) GetTypename() string {
	return v.Typename
}

// The query executed by Testing.
const Testing_Operation = `
query Testing {
	viewer {
		notificationThreads(first: 50, query: "is:read is:unread") {
			edges {
				cursor
				node {
					id
					oldestUnreadItemAnchor
					reason
					title
					isUnread
					isDone
					isSaved
					isStarred
					lastReadAt
					lastUpdatedAt
					url
					optionalSubject {
						__typename
						... on PullRequest {
							title
							body
							author {
								__typename
								... on User {
									name
									login
								}
								... on Bot {
									login
								}
							}
							merged
							closed
						}
					}
				}
			}
		}
	}
}
`

func Testing(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *TestingResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "Testing",
		Query:  Testing_Operation,
	}

	data_ = &TestingResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
